branch-defaults:
  master:
    environment: null
    group_suffix: null
environment-defaults:
  Productinfo-env:
    branch: null
    repository: null
global:
  application_name: productInfo
  branch: null
  default_ec2_keyname: product info
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Node.js running on
    64bit Amazon Linux/4.11.0
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
